name: affirmations_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  ###
  # Dependencies
  ###
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  geolocator: ^10.0.0
  intl: ^0.18.0
  location: ^5.0.3
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  go_router: ^10.1.2
  just_audio: ^0.9.35

  # Freezed
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  # UI
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  pull_down_button: ^0.9.3

  # Riverpod
  hooks_riverpod: ^2.4.0

  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  ###
  # Dev Dependencies
  ###
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  freezed: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/gradient/
    - assets/images/nature/
    - assets/images/sky/
